=begin
#The Selling Partner API for Invoices.

#Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.

OpenAPI spec version: 2024-06-19

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::InvoicesApiModel::GetInvoicesAttributesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetInvoicesAttributesResponse' do
  before do
    # run before each test
    @instance = AmzSpApi::InvoicesApiModel::GetInvoicesAttributesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetInvoicesAttributesResponse' do
    it 'should create an instance of GetInvoicesAttributesResponse' do
      expect(@instance).to be_instance_of(AmzSpApi::InvoicesApiModel::GetInvoicesAttributesResponse)
    end
  end
  describe 'test attribute "invoices_attributes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
