=begin
#Selling Partner API for Replenishment

#The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.

OpenAPI spec version: 2022-11-07

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::ReplenishmentApiModel::SellingpartnersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SellingpartnersApi' do
  before do
    # run before each test
    @instance = AmzSpApi::ReplenishmentApiModel::SellingpartnersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SellingpartnersApi' do
    it 'should create an instance of SellingpartnersApi' do
      expect(@instance).to be_instance_of(AmzSpApi::ReplenishmentApiModel::SellingpartnersApi)
    end
  end

  # unit tests for get_selling_partner_metrics
  # Returns aggregated replenishment program metrics for a selling partner.   **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
  # @param [Hash] opts the optional parameters
  # @option opts [GetSellingPartnerMetricsRequest] :body The request body for the &#x60;getSellingPartnerMetrics&#x60; operation.
  # @return [GetSellingPartnerMetricsResponse]
  describe 'get_selling_partner_metrics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
