=begin
#Selling Partner API for Retail Procurement Orders

#The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::VendorOrders::Decimal
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Decimal' do
  before do
    # run before each test
    @instance = AmzSpApi::VendorOrders::Decimal.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Decimal' do
    it 'should create an instance of Decimal' do
      expect(@instance).to be_instance_of(AmzSpApi::VendorOrders::Decimal)
    end
  end
end
