=begin
#The Selling Partner API for third party application integrations.

#With the AppIntegrations API v2024-04-01, you can send notifications to Amazon Selling Partners and display the notifications in Seller Central.

OpenAPI spec version: 2024-04-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ApplicationIntegrationsApiModel::RecordActionFeedbackRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RecordActionFeedbackRequest' do
  before do
    # run before each test
    @instance = AmzSpApi::ApplicationIntegrationsApiModel::RecordActionFeedbackRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecordActionFeedbackRequest' do
    it 'should create an instance of RecordActionFeedbackRequest' do
      expect(@instance).to be_instance_of(AmzSpApi::ApplicationIntegrationsApiModel::RecordActionFeedbackRequest)
    end
  end
  describe 'test attribute "feedback_action_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SELLER_ACTION_COMPLETED"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.feedback_action_code = value }.not_to raise_error
      # end
    end
  end

end
