=begin
#Selling Partner API for Data Kiosk

#The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.

OpenAPI spec version: 2023-11-15

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::DataKiosk20231115::GetQueriesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetQueriesResponse' do
  before do
    # run before each test
    @instance = AmzSpApi::DataKiosk20231115::GetQueriesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetQueriesResponse' do
    it 'should create an instance of GetQueriesResponse' do
      expect(@instance).to be_instance_of(AmzSpApi::DataKiosk20231115::GetQueriesResponse)
    end
  end
  describe 'test attribute "queries"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "pagination"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
