=begin
#Selling Partner API for Catalog Items

#Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).

OpenAPI spec version: 2022-04-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'catalog_items_2022_04_01/api_client'
require 'catalog_items_2022_04_01/api_error'
require 'catalog_items_2022_04_01/version'
require 'catalog_items_2022_04_01/configuration'

# Models
require 'catalog_items_2022_04_01/models/brand_refinement'
require 'catalog_items_2022_04_01/models/classification_refinement'
require 'catalog_items_2022_04_01/models/dimension'
require 'catalog_items_2022_04_01/models/dimensions'
require 'catalog_items_2022_04_01/models/error'
require 'catalog_items_2022_04_01/models/error_list'
require 'catalog_items_2022_04_01/models/item'
require 'catalog_items_2022_04_01/models/item_asin'
require 'catalog_items_2022_04_01/models/item_attributes'
require 'catalog_items_2022_04_01/models/item_browse_classification'
require 'catalog_items_2022_04_01/models/item_browse_classifications'
require 'catalog_items_2022_04_01/models/item_browse_classifications_by_marketplace'
require 'catalog_items_2022_04_01/models/item_classification_sales_rank'
require 'catalog_items_2022_04_01/models/item_contributor'
require 'catalog_items_2022_04_01/models/item_contributor_role'
require 'catalog_items_2022_04_01/models/item_dimensions'
require 'catalog_items_2022_04_01/models/item_dimensions_by_marketplace'
require 'catalog_items_2022_04_01/models/item_display_group_sales_rank'
require 'catalog_items_2022_04_01/models/item_identifier'
require 'catalog_items_2022_04_01/models/item_identifiers'
require 'catalog_items_2022_04_01/models/item_identifiers_by_marketplace'
require 'catalog_items_2022_04_01/models/item_image'
require 'catalog_items_2022_04_01/models/item_images'
require 'catalog_items_2022_04_01/models/item_images_by_marketplace'
require 'catalog_items_2022_04_01/models/item_product_type_by_marketplace'
require 'catalog_items_2022_04_01/models/item_product_types'
require 'catalog_items_2022_04_01/models/item_relationship'
require 'catalog_items_2022_04_01/models/item_relationships'
require 'catalog_items_2022_04_01/models/item_relationships_by_marketplace'
require 'catalog_items_2022_04_01/models/item_sales_ranks'
require 'catalog_items_2022_04_01/models/item_sales_ranks_by_marketplace'
require 'catalog_items_2022_04_01/models/item_search_results'
require 'catalog_items_2022_04_01/models/item_summaries'
require 'catalog_items_2022_04_01/models/item_summary_by_marketplace'
require 'catalog_items_2022_04_01/models/item_variation_theme'
require 'catalog_items_2022_04_01/models/item_vendor_details'
require 'catalog_items_2022_04_01/models/item_vendor_details_by_marketplace'
require 'catalog_items_2022_04_01/models/item_vendor_details_category'
require 'catalog_items_2022_04_01/models/pagination'
require 'catalog_items_2022_04_01/models/refinements'

# APIs
require 'catalog_items_2022_04_01/api/catalog_api'

module AmzSpApi::CatalogItems20220401
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::CatalogItems20220401.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
