=begin
#Selling Partner API for Tokens 

#The Selling Partner API for Tokens provides a secure way to access a customer's PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.  For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).

OpenAPI spec version: 2021-03-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'tokens_2021_03_01/api_client'
require 'tokens_2021_03_01/api_error'
require 'tokens_2021_03_01/version'
require 'tokens_2021_03_01/configuration'

# Models
require 'tokens_2021_03_01/models/create_restricted_data_token_request'
require 'tokens_2021_03_01/models/create_restricted_data_token_response'
require 'tokens_2021_03_01/models/error'
require 'tokens_2021_03_01/models/error_list'
require 'tokens_2021_03_01/models/restricted_resource'

# APIs
require 'tokens_2021_03_01/api/tokens_api'

module AmzSpApi::Tokens20210301
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::Tokens20210301.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
