=begin
#Selling Partner API for Direct Fulfillment Payments

#The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'vendor_direct_fulfillment_payments_v1/api_client'
require 'vendor_direct_fulfillment_payments_v1/api_error'
require 'vendor_direct_fulfillment_payments_v1/version'
require 'vendor_direct_fulfillment_payments_v1/configuration'

# Models
require 'vendor_direct_fulfillment_payments_v1/models/additional_details'
require 'vendor_direct_fulfillment_payments_v1/models/address'
require 'vendor_direct_fulfillment_payments_v1/models/charge_details'
require 'vendor_direct_fulfillment_payments_v1/models/decimal'
require 'vendor_direct_fulfillment_payments_v1/models/error'
require 'vendor_direct_fulfillment_payments_v1/models/error_list'
require 'vendor_direct_fulfillment_payments_v1/models/invoice_detail'
require 'vendor_direct_fulfillment_payments_v1/models/invoice_item'
require 'vendor_direct_fulfillment_payments_v1/models/item_quantity'
require 'vendor_direct_fulfillment_payments_v1/models/money'
require 'vendor_direct_fulfillment_payments_v1/models/party_identification'
require 'vendor_direct_fulfillment_payments_v1/models/submit_invoice_request'
require 'vendor_direct_fulfillment_payments_v1/models/submit_invoice_response'
require 'vendor_direct_fulfillment_payments_v1/models/tax_detail'
require 'vendor_direct_fulfillment_payments_v1/models/tax_registration_detail'
require 'vendor_direct_fulfillment_payments_v1/models/transaction_reference'

# APIs
require 'vendor_direct_fulfillment_payments_v1/api/vendor_invoice_api'

module AmzSpApi::VendorDirectFulfillmentPaymentsV1
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentPaymentsV1.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
