=begin
#Selling Partner API for Retail Procurement Shipments

#The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'vendor_shipments/api_client'
require 'vendor_shipments/api_error'
require 'vendor_shipments/version'
require 'vendor_shipments/configuration'

# Models
require 'vendor_shipments/models/address'
require 'vendor_shipments/models/carrier_details'
require 'vendor_shipments/models/carton'
require 'vendor_shipments/models/carton_reference_details'
require 'vendor_shipments/models/collect_freight_pickup_details'
require 'vendor_shipments/models/container_identification'
require 'vendor_shipments/models/container_item'
require 'vendor_shipments/models/container_sequence_numbers'
require 'vendor_shipments/models/containers'
require 'vendor_shipments/models/decimal'
require 'vendor_shipments/models/dimensions'
require 'vendor_shipments/models/duration'
require 'vendor_shipments/models/error'
require 'vendor_shipments/models/error_list'
require 'vendor_shipments/models/expiry'
require 'vendor_shipments/models/get_shipment_details_response'
require 'vendor_shipments/models/get_shipment_labels'
require 'vendor_shipments/models/import_details'
require 'vendor_shipments/models/inner_containers_details'
require 'vendor_shipments/models/item'
require 'vendor_shipments/models/item_details'
require 'vendor_shipments/models/item_quantity'
require 'vendor_shipments/models/label_data'
require 'vendor_shipments/models/location'
require 'vendor_shipments/models/money'
require 'vendor_shipments/models/package_item_details'
require 'vendor_shipments/models/packed_items'
require 'vendor_shipments/models/packed_quantity'
require 'vendor_shipments/models/pagination'
require 'vendor_shipments/models/pallet'
require 'vendor_shipments/models/party_identification'
require 'vendor_shipments/models/purchase_order_item_details'
require 'vendor_shipments/models/purchase_order_items'
require 'vendor_shipments/models/purchase_orders'
require 'vendor_shipments/models/route'
require 'vendor_shipments/models/shipment'
require 'vendor_shipments/models/shipment_confirmation'
require 'vendor_shipments/models/shipment_details'
require 'vendor_shipments/models/shipment_information'
require 'vendor_shipments/models/shipment_measurements'
require 'vendor_shipments/models/shipment_status_details'
require 'vendor_shipments/models/stop'
require 'vendor_shipments/models/submit_shipment_confirmations_request'
require 'vendor_shipments/models/submit_shipment_confirmations_response'
require 'vendor_shipments/models/submit_shipments'
require 'vendor_shipments/models/tax_registration_details'
require 'vendor_shipments/models/total_weight'
require 'vendor_shipments/models/transaction_reference'
require 'vendor_shipments/models/transport_label'
require 'vendor_shipments/models/transport_shipment_measurements'
require 'vendor_shipments/models/transportation_details'
require 'vendor_shipments/models/transportation_details_for_shipment_confirmation'
require 'vendor_shipments/models/transportation_labels'
require 'vendor_shipments/models/vendor_details'
require 'vendor_shipments/models/volume'
require 'vendor_shipments/models/weight'

# APIs
require 'vendor_shipments/api/vendor_shipping_api'

module AmzSpApi::VendorShipments
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorShipments.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
