=begin
#Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data

#The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.

OpenAPI spec version: 2021-10-28

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/api_client'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/api_error'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/version'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/configuration'

# Models
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/error'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/error_list'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/generate_order_scenario_request'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/order_scenario_request'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/pagination'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/party_identification'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/scenario'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/test_case_data'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/test_order'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/transaction'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/transaction_reference'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/models/transaction_status'

# APIs
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/api/vendor_df_sandbox_api'
require 'vendor_direct_fulfillment_sandbox_test_data_2021_10_28/api/vendor_df_sandboxtransactionstatus_api'

module AmzSpApi::VendorDirectFulfillmentSandboxTestData20211028
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::VendorDirectFulfillmentSandboxTestData20211028.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
