=begin
#The Selling Partner API for FBA inbound operations.

#The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.

OpenAPI spec version: 2024-03-20

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'date'

module AmzSpApi::FulfillmentInbound20240320
  class ItemLabelPageType
    A4_21 = 'A4_21'.freeze
    A4_24 = 'A4_24'.freeze
    A4_24_64X33 = 'A4_24_64x33'.freeze
    A4_24_66X35 = 'A4_24_66x35'.freeze
    A4_24_70X36 = 'A4_24_70x36'.freeze
    A4_24_70X37 = 'A4_24_70x37'.freeze
    A4_24I = 'A4_24i'.freeze
    A4_27 = 'A4_27'.freeze
    A4_40_52X29 = 'A4_40_52x29'.freeze
    A4_44_48X25 = 'A4_44_48x25'.freeze
    LETTER_30 = 'Letter_30'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ItemLabelPageType.constants.select { |c| ItemLabelPageType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ItemLabelPageType" if constantValues.empty?
      value
    end
  end
end
