=begin
#The Selling Partner API for FBA inbound operations.

#The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.

OpenAPI spec version: 2024-03-20

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'date'

module AmzSpApi::FulfillmentInbound20240320
  class ReasonComment
    APPOINTMENT_REQUESTED_BY_MISTAKE = 'APPOINTMENT_REQUESTED_BY_MISTAKE'.freeze
    VEHICLE_DELAY = 'VEHICLE_DELAY'.freeze
    SLOT_NOT_SUITABLE = 'SLOT_NOT_SUITABLE'.freeze
    OUTSIDE_CARRIER_BUSINESS_HOURS = 'OUTSIDE_CARRIER_BUSINESS_HOURS'.freeze
    UNFAVOURABLE_EXTERNAL_CONDITIONS = 'UNFAVOURABLE_EXTERNAL_CONDITIONS'.freeze
    PROCUREMENT_DELAY = 'PROCUREMENT_DELAY'.freeze
    SHIPPING_PLAN_CHANGED = 'SHIPPING_PLAN_CHANGED'.freeze
    INCREASED_QUANTITY = 'INCREASED_QUANTITY'.freeze
    OTHER = 'OTHER'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ReasonComment.constants.select { |c| ReasonComment::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ReasonComment" if constantValues.empty?
      value
    end
  end
end
