=begin
#The Selling Partner API for Automotive.

#The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.

OpenAPI spec version: 2024-11-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::Vehicles20241101::VehiclesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VehiclesApi' do
  before do
    # run before each test
    @instance = AmzSpApi::Vehicles20241101::VehiclesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VehiclesApi' do
    it 'should create an instance of VehiclesApi' do
      expect(@instance).to be_instance_of(AmzSpApi::Vehicles20241101::VehiclesApi)
    end
  end

  # unit tests for get_vehicles
  # Get the latest collection of vehicles
  # @param marketplace_id An identifier for the marketplace in which the resource operates.
  # @param vehicle_type An identifier for vehicle type.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_token A token to fetch a certain page when there are multiple pages worth of results.
  # @option opts [String] :updated_after Date in ISO 8601 format, if provided only vehicles which are modified/added to Amazon&#x27;s catalog after this date will be returned.
  # @return [VehiclesResponse]
  describe 'get_vehicles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
